# Generated by Django 2.2.4 on 2019-08-23 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='Friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
