# Generated by Django 2.2.4 on 2019-08-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20190829_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
    ]
