# Generated by Django 2.2.4 on 2019-08-26 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20190826_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='Friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
